import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Provider from "./_components/provider";
import {ClerkProvider} from "@clerk/nextjs";  



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const outfit = Outfit({ subsets: ["latin"], weight: ["400", "700"] });

import ClerkProviderWrapper from "../components/ClerkProvider";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={outfit.className}>
      <body>
        <ClerkProviderWrapper>
          <Provider>{children}</Provider>
        </ClerkProviderWrapper>
      </body>
    </html>
  );
}